Tracktor/design-system

- CHANGELOG.md
- package.json
- src/components/Feedback/Alert/stories/Alert.stories.tsx
- src/config/theme.ts
> update alert style

- .storybook/preview.tsx
- CHANGELOG.md
- package.json
- src/components/Inputs/QuantityField/QuantityField.tsx
- src/components/Inputs/QuantityField/index.ts
- src/components/Inputs/QuantityField/stories/QuantityField.stories.tsx
- src/components/Inputs/QuantityField/test/QuantityField.test.tsx
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/main.ts
> feat: add QuantityField

- CHANGELOG.md
- package.json
- src/components/Inputs/Select/stories/Select.stories.tsx
- src/config/theme.ts
> feat : add new select combinaison for text style

- CHANGELOG.md
- package.json
- src/components/Inputs/Select/stories/Select.stories.tsx
> docs : select checkmarks

- CHANGELOG.md
- package.json
- src/components/Surface/Paper/stories/Paper.stories.tsx
- src/config/theme.ts
> feat: update paper radius

- CHANGELOG.md
- README.md
- package.json
- src/components/Surface/Accordion/stories/Accordion.stories.tsx
- Add online storybook section in README.md
- Add new stories accordion
> docs : - Add online storybook section in README.md & new stories accordion

- CHANGELOG.md
- package.json
- yarn.lock
> chore : update dependencies

- .circleci/config.yml
- CHANGELOG.md
- README.md
- package.json
> chore : scope @tracktor

- CHANGELOG.md
- package.json
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/config/theme.tsx
> Fix picture file

- CHANGELOG.md
- package.json
- src/config/theme.tsx
> fix: input file selection file name

- CHANGELOG.md
> fix: autocomplete small size

- .eslintrc
- CHANGELOG.md
- colors.d.ts
- colors/index.d.ts
- colors/index.js
- package.json
> chore : improve colors module structure

- CHANGELOG.md
- package.json
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/config/theme.tsx
> feat : search field & fix file size field

- CHANGELOG.md
- package.json
- src/config/theme.tsx
> fix: check validity HTML5 onTextField type file

- CHANGELOG.md
- package.json
- src/components/DataDisplay/Chip/stories/Chip.stories.tsx
- src/components/Inputs/QuantityField/QuantityField.tsx
- src/components/Inputs/QuantityField/stories/QuantityField.stories.tsx
- src/config/theme.tsx
- src/constants/defaultFontWeight.ts
- src/constants/fonts.ts
- src/context/Theme/ThemeProvider.tsx
- vite.config.ts
- yarn.lock
> version 1.21.0

- CHANGELOG.md
- package.json
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/config/theme.tsx
> Textfield multiline

- CHANGELOG.md
- package.json
- src/components/Navigation/Menu/stories/Menu.stories.tsx
- src/components/Navigation/MenuList/stories/MenuList.stories.tsx
- src/components/Navigation/MenuList/stories/MenuList.tsx
- src/config/theme.tsx
> refactor(Menu): update style

- CHANGELOG.md
- package.json
- src/components/Inputs/Button/Button.tsx
- src/components/Inputs/Button/index.ts
- src/components/Inputs/Button/stories/Button.stories.tsx
- src/components/Inputs/Button/stories/Button.tsx
- src/main.ts
Add loading, loadingIndicator & loadingPosition props to Button component
> feat(Button):

- CHANGELOG.md
- package.json
- src/components/Inputs/Button/Button.tsx
- src/components/Inputs/Button/stories/Button.stories.tsx
> fix: button props

- CHANGELOG.md
- package.json
- src/components/Inputs/Button/Button.tsx
- src/components/Inputs/Button/stories/Button.stories.tsx
- src/components/Inputs/Button/stories/Button.tsx
- src/components/Navigation/Link/stories/Link.stories.tsx
- tsconfig.json
> [feat] : improve Button type

- CHANGELOG.md
- package.json
- src/context/Theme/ThemeProvider.tsx
- src/context/Theme/useThemeProvider.tsx
> feat: scroll bar style

- CHANGELOG.md
- package.json
- src/config/theme.tsx
- src/styles/colors/common.module.scss
> feat: update menu dark theme

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/MenuIcon/MenuIcon.tsx
- src/components/Navigation/NavigationMenu/MenuIcon/index.ts
- src/components/Navigation/NavigationMenu/MobileNavBar/MobileNavBar.tsx
- src/components/Navigation/NavigationMenu/MobileNavBar/index.ts
- src/components/Navigation/NavigationMenu/MobileNavBar/useMobileNavBar.ts
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/SecondaryMenuButton/SecondaryMenuButton.tsx
- src/components/Navigation/NavigationMenu/SecondaryMenuButton/index.ts
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
- src/components/Navigation/NavigationMenu/SideBar/index.ts
- src/components/Navigation/NavigationMenu/SideBarMenu/SideBarMenu.tsx
- src/components/Navigation/NavigationMenu/SideBarMenu/index.ts
- src/components/Navigation/NavigationMenu/TabletNavBar/TabletNavBar.tsx
- src/components/Navigation/NavigationMenu/TabletNavBar/index.ts
- src/components/Navigation/NavigationMenu/TextFieldSearch/TextFieldSearch.tsx
- src/components/Navigation/NavigationMenu/TextFieldSearch/index.ts
- src/components/Navigation/NavigationMenu/TextFieldSearch/useTextFieldSearch.ts
- src/components/Navigation/NavigationMenu/index.ts
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.tsx
- src/main.ts
> feat(Navigation)

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/SecondaryMenuButton/SecondaryMenuButton.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
[feat] :  Add loading state for secondaryMenu
[refactor] : Improve contrast for secondaryMenu
[refactor] : Change background color avatar
> feat(NavigationMenu):

- CHANGELOG.md
- package.json
- src/components/Surface/Card/stories/Card.stories.tsx
- src/config/theme.tsx
> fix(Card) : props square

- CHANGELOG.md
- package.json
- src/config/theme.tsx
- yarn.lock
> update: Tabs styles

- CHANGELOG.md
- package.json
- src/components/DataDisplay/List/stories/List.stories.tsx
- src/components/DataDisplay/ListItemCard/ListItemCard.tsx
- src/components/DataDisplay/ListItemCard/index.ts
- src/components/Inputs/Button/Button.tsx
- src/components/Inputs/Button/stories/Button.stories.tsx
- src/main.ts
> feat: add ListItemCard component

- CHANGELOG.md
- package.json
- src/components/DataDisplay/StatusIcon/StatusIcon.tsx
- src/components/DataDisplay/StatusIcon/index.ts
- src/components/DataDisplay/StatusIcon/stories/StatusIcon.stories.tsx
- src/components/DataDisplay/StatusIcon/stories/StatusIcon.tsx
- src/main.ts
> fix: add StatusIcon component

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/MobileNavBar/MobileNavBar.tsx
- src/components/Navigation/NavigationMenu/TabletNavBar/TabletNavBar.tsx
> fix: app bar

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/SecondaryMenuButton/SecondaryMenuButton.tsx
> feat: bottom menu id

- CHANGELOG.md
- package.json
- yarn.lock
> chore: dependencies upgrade

- CHANGELOG.md
- package.json
- src/components/Feedback/Lightbox/Lightbox.tsx
- src/components/Feedback/Lightbox/index.ts
- src/components/Feedback/Lightbox/stories/Lightbox.stories.tsx
- src/components/Feedback/Lightbox/stories/Lightbox.tsx
- src/main.ts
> version: 1.40.0

- CHANGELOG.md
- package.json
- src/components/Feedback/Dialog/DialogCloseIcon/DialogCloseIcon.tsx
- src/components/Feedback/Dialog/DialogCloseIcon/index.ts
- src/components/Feedback/Dialog/stories/Dialog.stories.tsx
- src/components/Icon/CloseIcon.tsx
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
- src/main.ts
> version: 1.42.0

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/MobileNavBar/MobileNavBar.tsx
- src/components/Navigation/NavigationMenu/MobileNavBar/useMobileNavBar.ts
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
- src/components/Navigation/NavigationMenu/utils/utils.ts
> version: 1.43.0

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/TextFieldSearch/TextFieldSearch.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
> version: 1.44.2

- CHANGELOG.md
- package.json
- src/components/Layout/IfFeatureEnable/IfFeatureEnable.tsx
- src/hooks/useFeatureEnabled/useFeatureEnabled.test.tsx
- src/hooks/useFeatureEnabled/useFeatureEnabled.ts
- src/main.ts
- vite.config.ts
> Improvement

- CHANGELOG.md
- package.json
- src/components/Navigation/TabPanel/TabPanel.tsx
- src/components/Navigation/TabPanel/index.ts
- src/components/Navigation/Tabs/stories/Tabs.stories.tsx
- src/hooks/useTabs/index.ts
- src/hooks/useTabs/useTabs.stories.mdx
- src/hooks/useTabs/useTabs.ts
- src/main.ts
> version: 1.45.0

- CHANGELOG.md
- package.json
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/theme.config.ts
> version: 1.46.4

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/TextFieldSearch/TextFieldSearch.tsx
- src/theme.config.ts
> version: 1.46.5

- CHANGELOG.md
- package.json
- src/components/DataDisplay/TypographySkeleton/TypographySkeleton.tsx
- src/components/DataDisplay/TypographySkeleton/index.ts
- src/components/DataDisplay/TypographySkeleton/stories/TypographySkeleton.stories.tsx
- src/components/DataDisplay/TypographySkeleton/stories/TypographySkeleton.tsx
- src/main.ts
> version: 1.48.0

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/NavLinkItem/NavLinkItem.tsx
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/SideBarMenu/SideBarMenu.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
> version: 1.49.0

- CHANGELOG.md
- package.json
- src/assets/img/tracktor-logo.svg
- src/components/DataDisplay/Logo/Logo.tsx
- src/components/DataDisplay/Logo/stories/Logo.stories.tsx
- src/components/DataDisplay/Logo/useLogo.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
> version: 1.50.0

- CHANGELOG.md
- package.json
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/context/Theme/ThemeProvider.tsx
> version: 1.53.1

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
> version: 1.53.2

- CHANGELOG.md
- package.json
- src/components/DataDisplay/Typography/stories/Typography.stories.tsx
- src/theme.ts
> version: 1.54.0

- CHANGELOG.md
- package.json
- src/config/theme.ts
- src/context/Theme/ThemeProvider.tsx
- src/context/Theme/useThemeProvider.tsx
- src/main.ts
> version: 1.55.1

- CHANGELOG.md
- package.json
- src/components/Inputs/Autocomplete/stories/Autocomplete.stories.tsx
- src/components/Inputs/Select/stories/Select.stories.tsx
- src/components/Inputs/TextField/stories/TextField.stories.tsx
- src/config/theme.ts
> version: 1.56.0

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
> Fix Navigation menu scroller

- CHANGELOG.md
- package.json
- src/config/theme.ts
> feat: version 1.57.0

- CHANGELOG.md
- package.json
- src/config/theme.ts
> fix: textField file not focusable with required form

- CHANGELOG.md
- package.json
- src/components/DataDisplay/TimeLine/TimeLineEventItem.tsx
> feat: version 2.0.0

- CHANGELOG.md
- package.json
- src/components/DataDisplay/TimeLine/TimeLineEventItem.tsx
- src/components/DataDisplay/TimeLine/stories/TimeLine.stories.tsx
> fix: tag timeline

- CHANGELOG.md
- package.json
- src/components/DataDisplay/ListAvatar/ListAvatar.tsx
- src/components/DataDisplay/ListAvatar/index.ts
- src/components/DataDisplay/ListAvatar/stories/ListAvatar.stories.tsx
- src/constants/colors.ts
> Avatar list

- CHANGELOG.md
- package.json
- src/components/DataDisplay/Icons/ArrowRightIcon.tsx
- src/components/DataDisplay/Icons/ChevronIcon.tsx
- src/components/DataDisplay/Icons/CloseIcon.tsx
- src/components/DataDisplay/TimeLine/TimeLine.tsx
- src/components/DataDisplay/TimeLine/TimeLineEventItem.tsx
- src/components/DataDisplay/TimeLine/stories/TimeLine.stories.tsx
> feat: new timeline variant

- CHANGELOG.md
- package.json
- src/components/Inputs/AutocompleteFilter/AutocompleteFilter.tsx
- src/components/Inputs/AutocompleteFilter/stories/AutocompleteFilter.stories.tsx
> Fix filter

- CHANGELOG.md
- package.json
- src/components/DataDisplay/FileViewer/FileViewer.tsx
> feat(fileviewer): add srcLightBox

- CHANGELOG.md
- package.json
- src/components/DataDisplay/Avatar/Avatar.tsx
- src/components/DataDisplay/Avatar/stories/Avatar.stories.tsx
> docs: storybook

- CHANGELOG.md
- package.json
- src/components/Feedback/Alert/stories/Alert.stories.tsx
- src/components/Feedback/Dialog/stories/Dialog.stories.tsx
- src/config/theme.tsx
> New alert variant

- CHANGELOG.md
- package.json
- src/components/Feedback/Dialog/DialogValidation/DialogValidation.tsx
> fix: dialog background

- CHANGELOG.md
- package.json
- src/components/Inputs/File/File.tsx
> feat: file forward ref

- CHANGELOG.md
- package.json
- src/components/DataDisplay/Chip/Chip.tsx
- src/components/DataDisplay/Chip/stories/Chip.stories.tsx
- src/config/theme.tsx
> feat: disable chip

- CHANGELOG.md
- package.json
- src/components/DataDisplay/ArticleImage/ArticleImage.tsx
- src/components/DataDisplay/ArticleImage/stories/ArticleImage.stories.tsx
- src/components/DataDisplay/Avatar/Avatar.tsx
> feat: double article image

- CHANGELOG.md
- package.json
- src/components/DataDisplay/ArticleImage/ArticleImage.tsx
- src/components/DataDisplay/ArticleImage/stories/ArticleImage.stories.tsx
- src/components/DataDisplay/Avatar/Avatar.tsx
> fix: double avatar/articleImage

- CHANGELOG.md
- package.json
- src/components/DataDisplay/FileViewer/FileViewer.tsx
This PR prevent the FileViewer to misinterpret EML as a picture.
> fix: make sure FileViewer handle mixed types (e.g. eml)

- CHANGELOG.md
- package.json
- src/components/DataDisplay/ArticleImage/ArticleImage.tsx
- src/components/DataDisplay/ArticleImage/stories/ArticleImage.stories.tsx
- src/components/DataDisplay/FileViewer/stories/basic-email.eml
> fix: qa radius and padding article image

- src/components/DataDisplay/FileViewer/FileViewer.tsx
- src/components/DataDisplay/FileViewer/stories/FileViewer.stories.tsx
> fix: tooltip FileViewer

- package.json
- src/components/DataDisplay/Icons/ChevronLeftDoubleIcon.tsx
- src/components/Navigation/NavigationMenu/NavigationMenu.tsx
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
- src/components/Navigation/NavigationMenu/SideBarMenu/SideBarMenu.tsx
- src/components/Navigation/NavigationMenu/stories/NavigationMenu.stories.tsx
- src/components/Surface/AppBar/AppBar.tsx
- yarn.lock
> feat : collapse backoffice menu

- CHANGELOG.md
- package.json
- src/components/Navigation/NavigationMenu/SideBar/SideBar.tsx
- src/components/Navigation/NavigationMenu/SideBarMenu/SideBarMenu.tsx
> fix: collapse nav menu pressable zone

- CHANGELOG.md
- package.json
- src/components/Inputs/ChipFilter/ChipFilter.tsx
- src/components/Inputs/ChipFilter/stories/ChipFilter.stories.tsx
> feat: add labelOnlyAfterSelection props to chip filter

- CHANGELOG.md
- package.json
- src/components/Inputs/AutocompleteFilter/AutocompleteFilter.tsx
- src/components/Inputs/AutocompleteFilter/stories/AutocompleteFilter.stories.tsx
- src/components/Inputs/ChipFilter/ChipFilter.tsx
> feat : autocomplete filter chip variant

- CHANGELOG.md
- package.json
- src/components/Inputs/File/File.tsx
- src/components/Inputs/File/stories/File.stories.tsx
> feat: controlled file input
